[package]
name = "tamasha"
version = "0.1.0"
authors = ["unrahul <rahulunair@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
reqwest = "0.11.0"
serde = "1.0.119"
serde_derive = "1.0.119"
serde_json = "1.0.61"
